name: snowflake-demo
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.11.9
  - snowflake-snowpark-python
  - pip
  - openssl=1.1.1
  - pip:
    # Snowflake
    - snowflake-cli-labs
